## Setup

In [20]:
# use full window width
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import os
import numpy as np
os.chdir('..')
import virl
from helper_methods import run, plot

## Agent Implementation

In [85]:
class QLearningAgent:

    def __init__(self, env,number_bins):
        self.num_of_actions = env.action_space.n
        #self.state_space =
        self.env = env
        self.number_bins = number_bins
        
        #self.q_table = np.zeros((number_bins**4,self.num_of_actions))
       
        
        # hyper parameters
        self.discount = 0.99 #gamma
        self.learning_rate = 0.2 #step size, alpha
        self.episodes = 20
        self.decrease_factor = 0.1
        
        
    def continous_to_discrete(self,continous,highest=600000000,lowest=0):
        bins = np.linspace(lowest,highest,num=self.number_bins)
        discrete = np.digitize(continous,bins)
        return discrete
    
    def run_all_episodes(self):
        all_states = []
        all_rewards = []
        epislon = 1 #at the start only explore
        
        for episode in range(self.episodes):
            states,rewards = self.run_episode(epislon)
            all_states.append(states)
            all_rewards.append(rewards)
            epislon -= self.decrease_factor #hyperparameter
            
        return all_states,all_rewards
    
    def run_episode(self,epislon):
        states = []
        rewards = []
        done = False
        
        
        state = self.env.reset()
        state = self.continous_to_discrete(state)
        states.append(state)
        while not done:
            random_number = np.random.randint(0,1)
            if random_number < epislon:
                #explore
                action = np.random.choice(self.num_of_actions)
                if action not in [0,1,2,3]:
                    print(action)
            else:
                #exploit
                action = self.get_action(state)
                if action not in [0,1,2,3]:
                    print("exploit")
                    print(action)
            new_state, reward, done, i = self.env.step(action=action) # Q-learning
            new_state = self.continous_to_discrete(new_state)
            
            #update q table
            self.update_q_table(state,new_state,action,reward)
            
            states.append(state)
            rewards.append(reward)
            state = new_state
        return (states, rewards)
    
    def update_q_table(self,state,new_state,action,reward):
        #target
        #max of a' given the 
        max_a_prime = np.max(self.q_table[new_state,:])
        target = reward + (self.discount*max_a_prime)
        
        #compute difference
        difference = target - self.q_table[state,action]
        
        #take a small step in the delta direction
        new_q = self.q_table[state,action] + (self.learning_rate * difference)
        print("---------")
        print(self.q_table)
        print(new_q)
        print(action)
        print("---------")
        self.q_table[state,action] = new_q
    
    def get_action(self,state):
        #exploit the q table
        action = np.argmax(self.q_table[state,:])
#         if action not in [0,1,2,3]:
#             print("exploit")
#             print(action)
#             print(self.q_table[state,:])
#             print(self.q_table.shape)
        return action
    
    def get_action_text(self):
        # ["no intervention", "impose a full lockdown", "implement track & trace", "enforce social distancing and face masks"]
        return "Text here"
    
    def get_env(self):
        return env
    
    def get_chart_title(self):
        return "Title here"


## Analysis

In [86]:
env = virl.Epidemic(stochastic=False, noisy=False)

agent = QLearningAgent(env,60)
states, rewards = agent.run_all_episodes()

plot(agent, states, rewards)

---------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[-9.75532956e-06 -9.75532956e-06 -9.75532956e-06 -9.75532956e-06]
0
---------
---------
[

 [-0.00087291 -0.01629148 -0.00440982 -0.00624059]]
[-0.00721512 -0.0202483  -0.0202483  -0.0202483 ]
1
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.00087291 -0.0202483  -0.00440982 -0.00624059]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.01141365 -0.04264728 -0.01123155 -0.01047978]
 [-0.01112761 -0.00789258 -0.00361737 -0.01998052]
 [-0.02499685 -0.01845086 -0.00551537 -0.00548731]
 [ 0.         -0.01140797  0.         -0.01998052]
 [ 0.         -0.03206353  0.          0.        ]
 [-0.01808947 -0.04496808  0.         -0.01998052]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02379923  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01808947  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.01845086  0.          0.        ]
 [ 0.          0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.00673729 -0.03842149 -0.01339672 -0.0095455 ]
 [-0.01112761 -0.00789258 -0.00361737 -0.01998052]
 [-0.02499685 -0.01845086 -0.00551537 -0.00548731]
 [ 0.         -0.01140797  0.         -0.01998052]
 [ 0.         -0.03206353  0.          0.        ]
 [-0.01808947 -0.04496808  0.         -0.01998052]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02379923  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01808947  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.01845086  0.          0.        ]
 [ 0.          0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.00557152 -0.03460361 -0.01341052 -0.00894293]
 [-0.01112761 -0.00789258 -0.00361737 -0.01998052]
 [-0.02499685 -0.01845086 -0.00551537 -0.00548731]
 [ 0.         -0.01140797  0.         -0.01998052]
 [ 0.         -0.03206353  0.          0.        ]
 [-0.01808947 -0.04496808  0.         -0.01998052]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02379923  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01808947  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.01845086  0.          0.        ]
 [ 0.          0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.01741329 -0.03460361 -0.02066351 -0.01091952]
 [-0.01332037 -0.03479469 -0.01396914 -0.01998052]
 [-0.02499685 -0.01845086 -0.02594701 -0.00548731]
 [-0.0342765  -0.01140797 -0.01974605 -0.01998052]
 [ 0.         -0.06685171 -0.01355697  0.        ]
 [-0.03736678 -0.04496808  0.         -0.01998052]
 [-0.01866341 -0.03791758  0.          0.        ]
 [ 0.         -0.04509514  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02605576  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01808947  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01934578  0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [ 0.          0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.00892372 -0.03793157 -0.01799968 -0.01044191]
 [-0.01332037 -0.03609775 -0.01512818 -0.02005327]
 [-0.02499685 -0.02984295 -0.02594701 -0.00548731]
 [-0.03279886 -0.01140797 -0.01974605 -0.01998052]
 [ 0.         -0.06685171 -0.01355697  0.        ]
 [-0.03736678 -0.04496808  0.         -0.01998052]
 [-0.01866341 -0.03791758  0.          0.        ]
 [ 0.         -0.04509514  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.02605576  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01808947  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01934578  0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [ 0.          0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.00877564 -0.04341794 -0.01717223 -0.01704074]
 [-0.01332037 -0.03609775 -0.02530059 -0.03823123]
 [-0.04665579 -0.02984295 -0.02594701 -0.02415349]
 [-0.03279886 -0.01140797 -0.01974605 -0.03086809]
 [ 0.         -0.06796033 -0.0354801  -0.01976364]
 [-0.05795063 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02463452 -0.01511707]
 [-0.01613819 -0.04509514 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.02605576  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.04252879  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01934578  0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [ 0.         -0.0144

 [-0.0017282  -0.03003621 -0.01205318 -0.01062536]]
[-0.01486904 -0.0161713  -0.0161713  -0.01861655]
2
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.00798982 -0.03732788 -0.0161713  -0.01301532]
 [-0.01197969 -0.03799557 -0.02530059 -0.03823123]
 [-0.04665579 -0.03384609 -0.02594701 -0.02415349]
 [-0.03279886 -0.02023522 -0.01974605 -0.03086809]
 [ 0.         -0.06796033 -0.0354801  -0.01976364]
 [-0.05795063 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02463452 -0.01511707]
 [-0.01613819 -0.04509514 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.02605576  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.04252879  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01934578  0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.00876988 -0.03670713 -0.01557932 -0.01220839]
 [-0.01197969 -0.04282762 -0.02829663 -0.03823123]
 [-0.04665579 -0.03384609 -0.02594701 -0.02415349]
 [-0.03279886 -0.02861934 -0.023853   -0.03086809]
 [ 0.         -0.06796033 -0.0354801  -0.01976364]
 [-0.05795063 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02463452 -0.01511707]
 [-0.01613819 -0.04509514 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.02605576  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.04252879  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.01934578  0.          0.          0.        ]
 [ 0.         -0.02336857  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01131407 -0.03915466 -0.01822433 -0.01405067]
 [-0.01427931 -0.04896024 -0.03098469 -0.0344148 ]
 [-0.04665579 -0.04379959 -0.02594701 -0.02415349]
 [-0.03279886 -0.02861934 -0.023853   -0.03086809]
 [ 0.         -0.06559077 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.03509964  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713  0.         -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [ 0.         -0.02575785 -0.00303178 -0.00202178]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.00470276 -0.03506658 -0.01734145 -0.0122456 ]
 [-0.01427931 -0.04896024 -0.03098469 -0.0344148 ]
 [-0.04665579 -0.04379959 -0.02594701 -0.02415349]
 [-0.03279886 -0.02861934 -0.023853   -0.03086809]
 [ 0.         -0.06559077 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.03509964  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713  0.         -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [-0.00099537 -0.03067672 -0.00518741 -0.00454711]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [-0.0035073  -0.0342

0
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.00389552 -0.03438932 -0.01615752 -0.01100659]
 [-0.01427931 -0.04896024 -0.03098469 -0.0344148 ]
 [-0.04665579 -0.04379959 -0.02594701 -0.02415349]
 [-0.03279886 -0.02861934 -0.023853   -0.03086809]
 [ 0.         -0.06559077 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.01319805 -0.03574805]
 [-0.01866341 -0.03791758 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.03509964  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713  0.         -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [-0.00096034 -0.03106068 -0.00518741 -0.00541421]
 [-0.00025281  0.         -0.0027393   0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.03861494  0.          0.        ]
 [-0.0035

 [-0.0032893  -0.03178866 -0.01282575 -0.0108307 ]]
[-0.01659499 -0.02223011 -0.0293933  -0.01010986]
3
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.01129902 -0.04174178 -0.02326584 -0.02223011]
 [-0.01892449 -0.04907193 -0.03017843 -0.0293933 ]
 [-0.05494204 -0.06109774 -0.03547354 -0.02509666]
 [-0.04245026 -0.04288992 -0.023853   -0.03248349]
 [ 0.         -0.07616693 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.05104498  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713 -0.01591491 -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [-0.00096034 -0.03106068 -0.00518741 -0.00541421]
 [-0.00025281 -0.01707045 -0.0027393   0.        ]
 [ 0.    

---------
[[ 0.          0.          0.          0.        ]
 [-0.01011785 -0.04139453 -0.02136103 -0.01703948]
 [-0.01892449 -0.04907193 -0.03017843 -0.02468419]
 [-0.05494204 -0.06109774 -0.03547354 -0.02509666]
 [-0.04245026 -0.04288992 -0.023853   -0.03248349]
 [ 0.         -0.07616693 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.05104498  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713 -0.01591491 -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [-0.00096034 -0.03106068 -0.00518741 -0.00541421]
 [-0.00025281 -0.01707045 -0.0027393   0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.04512229  0.          0.        ]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.00760793 -0.03590342 -0.01702694 -0.01297653]
 [-0.01892449 -0.04907193 -0.03017843 -0.02468419]
 [-0.05494204 -0.06109774 -0.03547354 -0.02509666]
 [-0.04245026 -0.04288992 -0.023853   -0.03248349]
 [ 0.         -0.07616693 -0.0354801  -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.02937337 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.02889334  0.          0.        ]
 [ 0.         -0.05104498  0.          0.        ]
 [ 0.          0.         -0.00514224 -0.00382981]
 [-0.03632441  0.         -0.00490614  0.        ]
 [ 0.         -0.00860713 -0.01591491 -0.0041589 ]
 [-0.01701066 -0.01853872  0.          0.        ]
 [-0.00096034 -0.03106068 -0.00518741 -0.00541421]
 [-0.00025281 -0.01707045 -0.0027393   0.        ]
 [ 0.          0.         -0.03216036  0.        ]
 [ 0.         -0.04512229  0.          0.        ]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01560942 -0.03869212 -0.0258423  -0.02213   ]
 [-0.02354018 -0.05520917 -0.04355872 -0.03161382]
 [-0.04331974 -0.06523685 -0.04425698 -0.03252805]
 [-0.04245026 -0.04850344 -0.03364498 -0.03248349]
 [ 0.         -0.07907804 -0.04300428 -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.03730618  0.          0.        ]
 [ 0.         -0.05104498  0.          0.        ]
 [ 0.          0.         -0.01296232 -0.00382981]
 [-0.03632441  0.         -0.00490614 -0.00753667]
 [ 0.         -0.00860713 -0.02090043 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.01175838]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [ 0.         -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.0342

[[ 0.          0.          0.          0.        ]
 [-0.01373455 -0.03860344 -0.02050931 -0.01958814]
 [-0.02354018 -0.05055839 -0.04355872 -0.02898655]
 [-0.04331974 -0.06523685 -0.04425698 -0.03252805]
 [-0.04245026 -0.04850344 -0.03364498 -0.03248349]
 [ 0.         -0.07907804 -0.04300428 -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.03730618  0.          0.        ]
 [ 0.         -0.05104498  0.          0.        ]
 [ 0.          0.         -0.01296232 -0.00382981]
 [-0.03632441  0.         -0.00490614 -0.00753667]
 [ 0.         -0.00860713 -0.02090043 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.01175838]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [ 0.         -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.03422058 -0.01

---------
[[ 0.          0.          0.          0.        ]
 [-0.02737719 -0.03822321 -0.01927878 -0.01655069]
 [-0.03507163 -0.05055839 -0.04355872 -0.02898655]
 [-0.04331974 -0.06523685 -0.04425698 -0.03252805]
 [-0.08042657 -0.04850344 -0.03364498 -0.03248349]
 [-0.04026682 -0.07907804 -0.04300428 -0.01976364]
 [-0.05174917 -0.0648678  -0.02647334 -0.03574805]
 [-0.0311419  -0.06322807 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.05186798  0.        ]
 [-0.01814952 -0.03730618  0.          0.        ]
 [-0.04026682 -0.05104498  0.          0.        ]
 [ 0.          0.         -0.01296232 -0.00382981]
 [-0.03632441  0.         -0.00490614 -0.00753667]
 [ 0.         -0.00860713 -0.02090043 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.01175838]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [ 0.         -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.02184471 -0.05016063 -0.01594276 -0.02798824]
 [-0.03507163 -0.04903071 -0.03904438 -0.02898655]
 [-0.04331974 -0.07890938 -0.04425698 -0.02963822]
 [-0.07842034 -0.04850344 -0.03364498 -0.03248349]
 [-0.04026682 -0.07611003 -0.04300428 -0.01976364]
 [-0.05174917 -0.06680304 -0.02647334 -0.03574805]
 [-0.0311419  -0.06829163 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.07979332 -0.05086078]
 [-0.01814952 -0.03730618  0.         -0.0167094 ]
 [-0.05373259 -0.05977235 -0.01189971 -0.01951429]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.00860713 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [-0.04498854 -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.0125448  -0.03850571 -0.0151096  -0.01948256]
 [-0.03507163 -0.04903071 -0.03904438 -0.02898655]
 [-0.04331974 -0.07890938 -0.04425698 -0.02963822]
 [-0.07842034 -0.04850344 -0.03364498 -0.03248349]
 [-0.04026682 -0.07611003 -0.04300428 -0.01976364]
 [-0.05174917 -0.06680304 -0.02647334 -0.03574805]
 [-0.0311419  -0.06829163 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.07979332 -0.05086078]
 [-0.01814952 -0.03730618  0.         -0.0167094 ]
 [-0.03456016 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.00860713 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [-0.04498854 -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.00964416 -0.04025949 -0.02261175 -0.0160593 ]
 [-0.0353618  -0.04920592 -0.03621361 -0.02898655]
 [-0.05338997 -0.07310886 -0.03954967 -0.02963822]
 [-0.07476679 -0.04850344 -0.03364498 -0.03248349]
 [-0.04026682 -0.08805047 -0.04300428 -0.01976364]
 [-0.06013351 -0.06680304 -0.02647334 -0.03574805]
 [-0.0311419  -0.06829163 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.07979332 -0.05086078]
 [-0.01814952 -0.05700739  0.         -0.0167094 ]
 [-0.03456016 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.00860713 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393   0.        ]
 [-0.00468858  0.         -0.03216036  0.        ]
 [-0.04498854 -0.04512229  0.         -0.00670401]
 [-0.0035073  -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01425985 -0.04436138 -0.02449977 -0.02012713]
 [-0.03188234 -0.05195762 -0.03621361 -0.03650257]
 [-0.05338997 -0.0695708  -0.03954967 -0.03099027]
 [-0.07476679 -0.05961611 -0.03661444 -0.03248349]
 [-0.04024816 -0.08693992 -0.04300428 -0.01976364]
 [-0.06013351 -0.07413315 -0.02647334 -0.04191177]
 [-0.0311419  -0.06829163 -0.03541187 -0.01511707]
 [-0.01613819 -0.04864868 -0.07979332 -0.05086078]
 [-0.01814952 -0.05700739  0.         -0.0167094 ]
 [-0.03456016 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393  -0.01331333]
 [-0.00468858  0.         -0.03216036  0.        ]
 [-0.04498854 -0.05259737  0.         -0.00670401]
 [-0.01084054 -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01540726 -0.04251035 -0.02208225 -0.02088744]
 [-0.03195373 -0.05265799 -0.03621361 -0.04164421]
 [-0.05338997 -0.06674853 -0.03954967 -0.03099027]
 [-0.06626129 -0.05961611 -0.04661603 -0.03939338]
 [-0.04024816 -0.08693992 -0.05172789 -0.0292175 ]
 [-0.06013351 -0.07413315 -0.02647334 -0.04191177]
 [-0.0311419  -0.06829163 -0.04565397 -0.01511707]
 [-0.01613819 -0.04864868 -0.07979332 -0.05086078]
 [-0.01814952 -0.05700739  0.         -0.0167094 ]
 [-0.03456016 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.00716588]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393  -0.01331333]
 [-0.00468858  0.         -0.03216036  0.        ]
 [-0.04498854 -0.05259737  0.         -0.00670401]
 [-0.01084054 -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.02378334 -0.04712167 -0.02208225 -0.02595932]
 [-0.03195373 -0.05265799 -0.04390478 -0.04164421]
 [-0.05338997 -0.06880474 -0.03954967 -0.03099027]
 [-0.05907737 -0.05961611 -0.04661603 -0.03939338]
 [-0.06899126 -0.08693992 -0.0662079  -0.03262337]
 [-0.05792475 -0.07413315 -0.02647334 -0.06390518]
 [-0.0311419  -0.06829163 -0.05145707 -0.04075034]
 [-0.01613819 -0.06191025 -0.07979332 -0.08550819]
 [-0.04050621 -0.05700739 -0.02482558 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.03610846]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393  -0.01331333]
 [-0.0098192  -0.01991505 -0.03216036 -0.00924937]
 [-0.04580878 -0.06506921 -0.01493389 -0.00670401]
 [-0.01084054 -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.00901874 -0.03697282 -0.02017606 -0.01541507]
 [-0.03195373 -0.05006279 -0.03968184 -0.03760273]
 [-0.05338997 -0.06880474 -0.03954967 -0.03099027]
 [-0.05907737 -0.05961611 -0.04661603 -0.03939338]
 [-0.06899126 -0.08693992 -0.0662079  -0.03262337]
 [-0.05792475 -0.07413315 -0.02647334 -0.06390518]
 [-0.0311419  -0.06829163 -0.05145707 -0.04075034]
 [-0.01613819 -0.06191025 -0.07979332 -0.08550819]
 [-0.04050621 -0.05700739 -0.02482558 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.0267199  -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05501927 -0.0041589 ]
 [-0.01701066 -0.01853872  0.         -0.03610846]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.02499356 -0.0027393  -0.01331333]
 [-0.00502538 -0.03209878 -0.02692699 -0.01050192]
 [-0.04580878 -0.06506921 -0.01493389 -0.00670401]
 [-0.01084054 -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01066048 -0.04490787 -0.02446645 -0.0221954 ]
 [-0.03195373 -0.05107955 -0.04353805 -0.03649632]
 [-0.05338997 -0.06591176 -0.04495854 -0.03606475]
 [-0.05907737 -0.06332814 -0.04744385 -0.03889185]
 [-0.06899126 -0.08693992 -0.0662079  -0.03367598]
 [-0.05792475 -0.07413315 -0.03116698 -0.06390518]
 [-0.0311419  -0.06829163 -0.05145707 -0.0438728 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.08550819]
 [-0.04050621 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.03610846]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.00502538 -0.03863341 -0.02692699 -0.01050192]
 [-0.03392241 -0.05810081 -0.01493389 -0.00670401]
 [-0.01084054 -0.0342

---------
[[ 0.          0.          0.          0.        ]
 [-0.01123318 -0.04356666 -0.02386631 -0.01996089]
 [-0.03195373 -0.05107955 -0.04353805 -0.03649632]
 [-0.05338997 -0.06591176 -0.04495854 -0.03606475]
 [-0.05907737 -0.06332814 -0.04744385 -0.03889185]
 [-0.06899126 -0.08693992 -0.0662079  -0.03367598]
 [-0.05792475 -0.07413315 -0.03116698 -0.06390518]
 [-0.0311419  -0.06829163 -0.05145707 -0.0438728 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.08550819]
 [-0.04050621 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.03610846]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.00502538 -0.03863341 -0.02692699 -0.01050192]
 [-0.03392241 -0.05810081 -0.01493389 -0.00670401]
 [-0.01129218 -0.0407

---------
[[ 0.          0.          0.          0.        ]
 [-0.01098827 -0.04351069 -0.02258086 -0.01769863]
 [-0.02753396 -0.05107955 -0.04353805 -0.03649632]
 [-0.05338997 -0.06591176 -0.04495854 -0.03606475]
 [-0.05907737 -0.06332814 -0.04744385 -0.03889185]
 [-0.06899126 -0.08693992 -0.0662079  -0.03367598]
 [-0.05792475 -0.07413315 -0.03116698 -0.06390518]
 [-0.0311419  -0.06829163 -0.05145707 -0.0438728 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.08550819]
 [-0.04050621 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.00382981]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.03610846]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.00502538 -0.03863341 -0.02692699 -0.01050192]
 [-0.03392241 -0.05810081 -0.01493389 -0.00670401]
 [-0.01129218 -0.0407

 [-0.00918985 -0.03942673 -0.02005546 -0.01658132]]
[-0.03676889 -0.01561817 -0.01561817 -0.00077806]
0
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.01561817 -0.04393858 -0.02113035 -0.02509088]
 [-0.02740662 -0.0620143  -0.03811002 -0.04121648]
 [-0.05175918 -0.06304391 -0.04367488 -0.04117086]
 [-0.04877417 -0.06332814 -0.04744385 -0.05642654]
 [-0.07745383 -0.08854081 -0.0662079  -0.04685273]
 [-0.05792475 -0.07652451 -0.03116698 -0.07172354]
 [-0.0311419  -0.0800173  -0.0488737  -0.0641904 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.07746199]
 [-0.04145217 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.01844648]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.04811643]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.0262

---------
[[ 0.          0.          0.          0.        ]
 [-0.01173118 -0.03849672 -0.01867108 -0.01449679]
 [-0.02740662 -0.0620143  -0.03811002 -0.04121648]
 [-0.05175918 -0.06304391 -0.04367488 -0.04117086]
 [-0.04877417 -0.06332814 -0.04744385 -0.05642654]
 [-0.07745383 -0.08854081 -0.0662079  -0.04685273]
 [-0.05792475 -0.07652451 -0.03116698 -0.07172354]
 [-0.0311419  -0.0800173  -0.0488737  -0.0641904 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.07746199]
 [-0.04145217 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.01844648]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.04811643]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.02628112 -0.03863341 -0.02692699 -0.01050192]
 [-0.03392241 -0.05810081 -0.01493389 -0.00670401]
 [-0.01129218 -0.0407

 [-0.01014939 -0.03942673 -0.02005546 -0.01658132]]
[-0.00743593 -0.02427705 -0.03671797 -0.045391  ]
2
---------
---------
[[ 0.          0.          0.          0.        ]
 [-0.01201513 -0.03979962 -0.02427705 -0.01846044]
 [-0.02740662 -0.05638723 -0.03671797 -0.03483305]
 [-0.05175918 -0.05993141 -0.04367488 -0.04117086]
 [-0.04877417 -0.06332814 -0.045391   -0.04972499]
 [-0.07745383 -0.08854081 -0.0662079  -0.04685273]
 [-0.05792475 -0.07652451 -0.03116698 -0.07172354]
 [-0.0311419  -0.0800173  -0.0488737  -0.0641904 ]
 [-0.01613819 -0.06191025 -0.07979332 -0.07746199]
 [-0.04145217 -0.05700739 -0.03347794 -0.0167094 ]
 [-0.04920544 -0.04331063 -0.01225879 -0.01547271]
 [ 0.         -0.03713391 -0.01296232 -0.01844648]
 [-0.08663493  0.         -0.00490614 -0.05689011]
 [ 0.         -0.02757642 -0.05416644 -0.0041589 ]
 [-0.01701066 -0.02739841  0.         -0.04811643]
 [-0.00096034 -0.03106068 -0.00518741 -0.06026748]
 [-0.00025281 -0.03119109 -0.00961406 -0.01331333]
 [-0.0262

AssertionError: 

## Evaluation

Eval here